name: ci

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract package version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PUSH_TOKEN }}
      - name: Build and push to GitHub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ghcr.io/topahl/hass-lovelace-kobo-screensaver:${{ env.PACKAGE_VERSION }},
            ghcr.io/topahl/hass-lovelace-kobo-screensaver:latest
      - name: Build and push HA_Addon AMD64 to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.HA_ADDON
          build-args: BUILD_FROM=homeassistant/amd64-base:latest
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/topahl/hass-lovelace-kobo-screensaver-ha-addon-amd64:${{ env.PACKAGE_VERSION }},
            ghcr.io/topahl/hass-lovelace-kobo-screensaver-ha-addon-amd64:latest
      - name: Build and push HA_Addon aarch64 to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.HA_ADDON
          build-args: BUILD_FROM=homeassistant/aarch64-base:latest
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/topahl/hass-lovelace-kobo-screensaver-ha-addon-aarch64:${{ env.PACKAGE_VERSION }},
            ghcr.io/topahl/hass-lovelace-kobo-screensaver-ha-addon-aarch64:latest
      - name: Tag git commit
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.REPO_GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ env.PACKAGE_VERSION }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"
          